### PR TITLE
Port to stable Rust. (Use the void crate instead of the never type.)

### PR DESCRIPTION
**Pull request by SimonSapin**
Hi. I’m submitting this as part of the effort to reduce Servo’s (and its dependencies’) usage of unstable language features: https://github.com/servo/servo/issues/5286.

Using an empty enum instead is not as theoretically pleasing as the `!` type, but I think it’s worth it as it has little practical consequences. What do you think?

(Making this version 0.5 because it changes public APIs.)

### CODE REVIEW

**Comment by clarcharr** [comment]
Thanks for the change! This crate actually needs to be updated to use the latest version of `len-trait` and co. anyway, so, I'll look at this over the weekend and merge both this and that.

**Comment by SimonSapin** [comment]
Cool, thanks!

I also have patches to update `parse-hosts` to multistr 0.4, but I’ll submit a PR to update to 0.5 directly once that’s on crates.io. (Unless you prefer I submit now.)

**Comment by clarcharr** [comment]
Feel free to submit the current patches! I'll ping you in those threads once I've updated for 0.5.

I'll make sure that the changes I make work on the latest stable.

**Comment by SimonSapin** [comment]
> I'll make sure that the changes I make work on the latest stable.

I suggest setting up https://travis-ci.org/ with a `.travis.yml` file like this:

```yaml
language: rust
rust:
  - nightly
  - beta
  - stable
```

**Comment by SimonSapin** [comment]
Friendly ping :)

**Comment by clarcharr** [comment]
@SimonSapin I ended up factoring this into the existing changes I made, so that I don't have to push two new versions. I'm going to revamp this mess of a crate once I get `len-trait` and co. finished and stable. Thanks for bringing this to my attention! :)

(right now `len-trait` relies on `OsString::shrink_to_fit`, which will be rolling out in 1.19. so, this will only work on 1.19 and above)

**Comment by SimonSapin** [comment]
Thanks… but depending on the unstable `osstring_shrink_to_fit` feature kind of defeats the purpose.

**Comment by SimonSapin** [comment]
Ok, this doesn’t build in 1.19.0-beta.2, but hopefully it will in beta.3 since https://github.com/rust-lang/rust/pull/42745 is "beta-accepted".

Thank you for taking care of this!

**Pull request closed without merging**
